# OpenShift variables

master_url: https://192.168.137.2:8443
username: developer
password: developer
admin_username: admin
admin_password: admin

project_name: summit-game

# Score server
score_user: kieserver
score_password: ki3server@

# Maven repository - unset this if not present
maven_mirror_url: http://nexus.nexus.svc.cluster.local:8081/repository/maven-public/

# Repositories
game_server_repo: https://github.com/burrsutter/vertx-game-server

# Repo below instead of Burr's fixes hibernate issue when compiling
score_server_repo: https://github.com/gnunn1/score-server

# Note the achievement server was re-written from EAP to vert.x, this playbook expects the vert.x version
achievement_server_repo: https://github.com/burrsutter/vertx-achievement-service

# Repo uses a URL based on location so it doesn't have to be changed anymore
mobile_app_repo: https://github.com/gnunn1/mobile-app

# Repo uses a URL based on location so it doesn't have to be changed anymore
mobile_admin_app_repo: https://github.com/gnunn1/mobile-app-admin

# Repo uses a URL based on location so it doesn't have to be changed anymore
scoreboard_repo: https://github.com/gnunn1/scoreboard

# Repo uses a URL based on location so it doesn't have to be changed anymore
leaderboard_repo: https://github.com/eformat/leaderboard
