---
- name: Create leaderboard application
  command: "oc new-app openshift/nodejs:6~{{ leaderboard_repo }}"

- name: Expose route for leaderboard application
  command: "oc expose svc leaderboard"

- name: Wait for leaderboard application to be ready
  command: "oc get ep leaderboard"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 15