---
- name: Create mobile game application
  command: "oc new-app openshift/nodejs:4~{{ mobile_app_repo }}"

- name: Expose route for mobile app application
  command: "oc expose svc mobile-app"

- name: Wait for game application to be ready
  command: "oc get ep mobile-app"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 15