---
- name: Create scoreboard application
  command: "oc new-app openshift/nodejs:6~{{ scoreboard_repo }}"

- name: Expose route for scoreboard application
  command: "oc expose svc scoreboard"

- name: Wait for scoreboard application to be ready
  command: "oc get ep scoreboard"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 15