---
- name: Setup up mobile admin application
  command: "oc new-app openshift/nodejs:6~{{ mobile_admin_app_repo }}"

- name: Expose route for mobile admin application
  command: "oc expose svc mobile-app-admin"

- name: Wait for admin application to be ready
  command: "oc get ep mobile-app-admin"
  register: result
  until: result.stdout.find("none") == -1
  retries: 50
  delay: 15